### ISSUE TITLE
parse rule falied, invalid content option "byte_extract" with no content match

### ISSUE THREAD

**Issue by chuanjiesun** [google/gonids#47]
parse rule failed:
**alert tcp $HOME_NET any -> $EXTERNAL_NET any (msg:"TROJAN Backdoor family PCRat/Gh0st CnC traffic (OUTBOUND) 14"; flow:to_server,established; dsize:>11; byte_extract:4,0,c_size,little; byte_test:4,>,c_size,4,little; content:"|08 01|"; offset:2; depth:2; content:"|79 94|"; offset:13; depth:2; pcre:"/^.{8}[\x20-\x7e]+?\x79\x94/s"; reference:url,www.securelist.com/en/descriptions/10155706/Trojan-GameThief.Win32.Magania.eogz; reference:url,www.microsoft.com/security/portal/Threat/Encyclopedia/Entry.aspx?Name=Backdoor%3AWin32%2FPcClient.ZR&ThreatID=-2147325231; reference:md5,9fae15fa8ab6bb8d78d609bdceafe28e; classtype:trojan-activity; sid:2017944; rev:5; metadata:affected_product Windows_XP_Vista_7_8_10_Server_32_64_Bit, attack_target Client_Endpoint, deployment Perimeter, tag PCRAT, tag Gh0st, tag RAT, signature_severity Critical, created_at 2014_01_08, malware_family Gh0st, malware_family PCRAT, updated_at 2016_07_01;)**
error message is : invalid content option "byte_extract" with no content match, how to solve it?

**Comment by duanehoward** [comment]
We currently require byte_extract to be related to a content match, this may not be correct, and we will need to consult the Snort language specification for this one. Suricata's documentation around  this keyword doesn't appear to be very detailed. I probably won't get to this for at least a week.

**Comment by duanehoward** [comment]
This Snort rule specification in section `3.5.33 byte extract`:

- Has no requirement about this being tied directly to a `Content`
- Indicates that at *most* 2 variables per rule may be created (not sure if Suricata has this same requirement)

Currently we treat `byte_extract` as a `ContentOption` which is not correct.

Because we also need to be able to keep these in order (as they depend on the current cursor for the rule, and can be relative to a `Content` match) we need to ensure that they are self contained so that we can write individual stringers on them.

To do achieve this we can no longer depend on a `map[string]*Var` to encode the name, unless we want to do strange iteration loops and matching to write out the string.
I'm proposing that we change from:
```
Vars map[string]*Var

type Var struct {
	NumBytes int
	Offset   int
	Options  []string
}
```
to:
```
Vars []*Var

type Var struct {
	NumBytes int
	Offset   int
	Name     string
	Options  []string
}
```

Additionally the `byte_math` keyword is supported by Snort and has a similar structure, but I don't see references to it in the Suricata docs, so probably don't need to worry about it for now.

**Comment by duanehoward** [comment]
@julienschmidt heads up that I'm probably going to make this change in the next week or two depending on available time. I know you have dependencies on this structure, and it will probably break you. Should be a relatively simple refactor though.

**Comment by duanehoward** [comment]
After I've partially implemented this and started to think about String() output for rules, I've realized we need some level of support for `byte_test` and `byte_jump` and probably others. This requires some additional thought into what the correct structure for this is. Possibly we'll leave the `Vars` structure alone as a map, and not rely on it at all for String output, but create something like a `ByteMatch` struct that can potentially represent all of these operations.

Rough sketch is:
```
type byteMatcher int
const (
    extract byteMatcher = iota
    test
    jump
)

type ByteMatch struct {
    Kind byteMatcher
    Variable string
    NumBytes int
    Offset int
    // Other specifics required for jump/test here
    Options []string
}
```

**Comment by duanehoward** [comment]
Alternately we could leave the `byte_jump` and `byte_test` bits as `Tags` but add them to the `Matchers` to ensure that they get written at a certain point, however this will introduce complexity to the Stringer for writing `Rule` as we'll need to skip writing those (they'll be written as part of the `Matchers` write.

**Comment by duanehoward** [comment]
Doh. I was accidentally working on this in master and committed without meaning to. Regardless this should be fixed. Additional support for byte_jump and byte_test coming soon.
See commit https://github.com/google/gonids/commit/99de17dc22a2b13a697a2c3b749ffb5842c374cb
